version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo In pre_build phase
  build:
    commands:
      - echo Build started on `date`
      - gradle bootJar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/**